### ISSUE TITLE
Doesn't update when navigating between pages in a single page app

### ISSUE THREAD

**Issue by mattconde** [contentstack/contentstack-chrome-extension#5]
I have added support within our single page app, works fine on a full reload on the page. But when dynamically updating the `pageref` the link doesn't update with it.

Would love for the extension to update if the dataset `pageref` is updated.

**Comment by Amitkanswal** [comment]
Hey mattconde, we have resolved this issue in the latest version of our extension. Please update to the latest version and let us know if you are still facing the same issue. Thank you

**Comment by imkhan** [comment]
@mattconde , Hope the issue is resolved for you. We've marked this issue as resolved, but if there are any further questions, please tag me in your reply and we will be happy to continue the conversation.

**Comment by mattconde** [comment]
Yeah perfect - that resolved the issue for me. Thanks both.
