### ISSUE TITLE
Feature Request: Subdomain Config Support

### ISSUE THREAD

**Issue by richardpj** [contentstack/contentstack-chrome-extension#8]
We have a setup that looks something like this:

1 Stack A
- Dev: dev.SomeBigCompany.com
- Prod: SomeBigCompany.com

2 Stack B
- Dev: dev-subsidiary.SomeBigCompany.com
- Prod: Subsidiary.com

The config validation linked with the fact that the sites are not optionally differentiated by subdomain means that the incorrect API key is picked up by the plugin in this case.

Please can you add this to your backlog.

Please contact me for better real-world test cases (which I can only share by email).

**Comment by imkhan** [comment]
@richardpj , thanks for reaching out with this request. 
We've added this in our backlog, we'll update you as soon as we resolved it.

**Comment by richardpj** [comment]
Great news! Thanks @imkhan ! If you need a concrete example of our challenge please share an email address and I'll forward you more details on our actual setup.

**Comment by richardpj** [comment]
The addon seems to have been updated. The host/domain config now meets our requirement! Thanks @imkhan! I'm going to close this as resolved.
